"use client";

export const dynamic = "force-dynamic";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { Icon } from "@/components/Icon";

const palette = { forest:"#1F3D2B", navy:"#1F2A44", gold:"#C8A24D" };
type ReviewRow={id:string;request_id:string;borrower_id:string|null;owner_id:string|null;horse_id:string|null;rating:number|null;comment:string|null;created_at?:string|null};
type BorrowRequestMini={id:string;start_date:string|null;end_date:string|null};
type HorseMini={id:string;name:string|null};
type ProfileMini={id:string;display_name:string|null;full_name:string|null};

function fmtDate(d:string|null|undefined){if(!d)return"—";try{return new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});}catch{return String(d)}}
function personName(profile:ProfileMini|null|undefined){return profile?.display_name?.trim()||profile?.full_name?.trim()||"Member"}
function renderStars(rating:number|null|undefined){const value=Math.max(0,Math.min(5,Number(rating??0)));return"★".repeat(value)+"☆".repeat(5-value)}

export default function OwnerReviewsPage(){
 const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[reviews,setReviews]=useState<ReviewRow[]>([]);const[horsesById,setHorsesById]=useState<Record<string,HorseMini>>({});const[borrowersById,setBorrowersById]=useState<Record<string,ProfileMini>>({});const[requestsById,setRequestsById]=useState<Record<string,BorrowRequestMini>>({});
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError(null);try{const{data:{user},error:userErr}=await supabase.auth.getUser();if(userErr)throw userErr;if(!user)throw new Error("Not authenticated");const{data:reviewsData,error:reviewsErr}=await supabase.from("reviews").select("id,request_id,borrower_id,owner_id,horse_id,rating,comment,created_at").eq("owner_id",user.id).order("id",{ascending:false});if(reviewsErr)throw reviewsErr;const reviewRows=(reviewsData??[])as ReviewRow[];if(cancelled)return;setReviews(reviewRows);const horseIds=Array.from(new Set(reviewRows.map(r=>r.horse_id).filter(Boolean)as string[]));const borrowerIds=Array.from(new Set(reviewRows.map(r=>r.borrower_id).filter(Boolean)as string[]));const requestIds=Array.from(new Set(reviewRows.map(r=>r.request_id).filter(Boolean)));const[horsesRes,borrowersRes,requestsRes]=await Promise.all([horseIds.length?supabase.from("horses").select("id,name").in("id",horseIds):Promise.resolve({data:[],error:null}as any),borrowerIds.length?supabase.from("public_profiles").select("id,display_name,full_name").in("id",borrowerIds):Promise.resolve({data:[],error:null}as any),requestIds.length?supabase.from("borrow_requests").select("id,start_date,end_date").in("id",requestIds):Promise.resolve({data:[],error:null}as any)]);if(horsesRes.error)throw horsesRes.error;if(borrowersRes.error)throw borrowersRes.error;if(requestsRes.error)throw requestsRes.error;if(cancelled)return;const hm:Record<string,HorseMini>={};for(const h of(horsesRes.data??[])as HorseMini[])hm[h.id]=h;const bm:Record<string,ProfileMini>={};for(const b of(borrowersRes.data??[])as ProfileMini[])bm[b.id]=b;const rm:Record<string,BorrowRequestMini>={};for(const r of(requestsRes.data??[])as BorrowRequestMini[])rm[r.id]=r;setHorsesById(hm);setBorrowersById(bm);setRequestsById(rm)}catch(e:any){if(!cancelled)setError(e?.message??"Failed to load reviews.")}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[]);
 const reviewCount=reviews.length;const averageRating=useMemo(()=>{const valid=reviews.map(r=>Number(r.rating)).filter(n=>Number.isFinite(n)&&n>0);if(!valid.length)return null;return(valid.reduce((s,n)=>s+n,0)/valid.length).toFixed(1)},[reviews]);const fiveStarCount=useMemo(()=>reviews.filter(r=>Number(r.rating)===5).length,[reviews]);const withCommentCount=useMemo(()=>reviews.filter(r=>Boolean(r.comment?.trim())).length,[reviews]);
 return <div className="pmp-pageShell"><style>{`
 .pmp-reviewGrid{display:grid;gap:12px}.pmp-reviewCard{border:1px solid rgba(31,42,68,.10);border-radius:18px;background:#fff;padding:16px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px}.pmp-reviewActions{display:flex;flex-direction:column;gap:10px;min-width:150px}.pmp-reviewActions a{width:100%;box-sizing:border-box;justify-content:center}.pmp-reviewDates{display:flex;gap:5px;flex-wrap:wrap}.pmp-reviewComment{margin-top:12px;font-size:13px;color:rgba(31,42,68,.78);line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere}
 @media(max-width:640px){.pmp-reviewCard{grid-template-columns:1fr;padding:14px}.pmp-reviewActions{min-width:0;width:100%;display:grid;grid-template-columns:1fr}.pmp-reviewActions a{min-height:44px}.pmp-reviewDates{display:block}.pmp-reviewDates span{display:inline}.pmp-reviewCard *{min-width:0}.pmp-reviewGrid{gap:10px}}
 `}</style>
 <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div className="pmp-kicker">My horse feedback</div><h1 className="pmp-pageTitle">Reviews</h1><div className="pmp-mutedText" style={{marginTop:6}}>Feedback left by members after approved bookings.</div></div></div>
 <section className="pmp-statGrid" style={{marginTop:16}}><article className="pmp-statCard"><div className="pmp-statLabel">Total reviews</div><div className="pmp-statValue">{reviewCount}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">Average rating</div><div className="pmp-statValue">{averageRating??"—"}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">5 star reviews</div><div className="pmp-statValue">{fiveStarCount}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">With comments</div><div className="pmp-statValue">{withCommentCount}</div></article></section>
 {loading?<div style={{marginTop:16}} className="pmp-mutedText">Loading…</div>:null}{error?<div className="pmp-errorBanner" style={{marginTop:16}}>{error}</div>:null}
 <section className="pmp-sectionCard" style={{marginTop:16}}><div className="pmp-sectionHeader"><div><div className="pmp-kicker">Member feedback</div><h3 className="pmp-sectionTitle">Recent reviews</h3></div><div className="pmp-mutedText">{reviewCount} review{reviewCount===1?"":"s"}</div></div>
 {!loading&&!error&&reviews.length===0?<div className="pmp-emptyState"><div className="pmp-emptyIcon"><Icon name="heart" size={31}/></div><div className="pmp-emptyTitle">No reviews yet</div><div className="pmp-emptyText">Reviews will appear here once members leave feedback after their booking.</div></div>:<div className="pmp-reviewGrid">{reviews.map(review=>{const horse=review.horse_id?horsesById[review.horse_id]:null;const borrower=review.borrower_id?borrowersById[review.borrower_id]:null;const request=requestsById[review.request_id]??null;return <article key={review.id} className="pmp-reviewCard"><div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><div style={{fontSize:18,lineHeight:1,letterSpacing:1,color:palette.gold,fontWeight:900}}>{renderStars(review.rating)}</div><div style={{fontSize:13,fontWeight:900,color:palette.navy}}>{Number(review.rating??0)}/5</div></div><div style={{marginTop:10,fontSize:16,fontWeight:950,color:palette.navy}}>{horse?.name??"Horse"}</div><div style={{marginTop:6,fontSize:13,color:"rgba(31,42,68,.70)",lineHeight:1.5}}>Member: <strong>{personName(borrower)}</strong></div><div style={{marginTop:4,fontSize:13,color:"rgba(31,42,68,.70)",lineHeight:1.5}} className="pmp-reviewDates">Booking: <strong>{fmtDate(request?.start_date)} → {fmtDate(request?.end_date)}</strong></div><div className="pmp-reviewComment">{review.comment?.trim()||"No written comment provided."}</div></div><div className="pmp-reviewActions"><Link href={`/messages/${review.request_id}`} className="pmp-ctaSecondary">View thread</Link>{review.horse_id?<Link href={`/dashboard/owner/horses/${review.horse_id}/availability`} className="pmp-ctaSecondary">Availability</Link>:null}</div></article>})}</div>}
 </section></div>;
}
