# frozen_string_literal: true

opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Upload an existing IPA to TestFlight"
  lane :upload_only do
    upload_to_testflight(
      username: ENV["FASTLANE_USER"],
      apple_id: ENV["APPLE_APP_ID"],
      ipa: "build/export/App.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end