default_platform(:ios)

platform :ios do
  desc "ONE-TIME: create signing certs/profiles and store in match repo"
  lane :bootstrap do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_P8"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      git_url: ENV["MATCH_GIT_URL"],
      readonly: false,
      api_key: api_key,
      username: ENV["FASTLANE_USER"] # prevents interactive username prompt in CI
    )
  end

  desc "Build + upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_P8"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      git_url: ENV["MATCH_GIT_URL"],
      readonly: true,
      api_key: api_key,
      username: ENV["FASTLANE_USER"]
    )

    build_app(
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end