'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { Icon } from '@/components/Icon';

type ProfileMini={id:string;display_name:string|null;full_name:string|null};
type Ride={id:string;status:string;start_date:string|null;end_date:string|null;message:string|null;horse:{id:string;name:string|null;image_url:string|null;image_urls:string[]|null}|null;horse_id:string|null;borrower_name:string};

function ownerLabel(p?:ProfileMini|null){return p?.display_name?.trim()||p?.full_name?.trim()||'Owner'}
function fmtDate(value:string|null){if(!value)return'—';try{return new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}catch{return value.slice(0,10)}}

export default function MyRidesPage(){
 const[myUserId,setMyUserId]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[rides,setRides]=useState<Ride[]>([]),[reviewedRequestIds,setReviewedRequestIds]=useState<Set<string>>(new Set());
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError(null);try{
  const{data:auth,error:authErr}=await supabase.auth.getUser();if(authErr)throw authErr;const uid=auth?.user?.id??null;
  if(!uid){if(!cancelled){setMyUserId(null);setRides([])}return}if(!cancelled)setMyUserId(uid);
  const{data:reqs,error:reqErr}=await supabase.from('borrow_requests').select('id,status,start_date,end_date,message,horse:horses!borrow_requests_horse_id_fkey(id,name,owner_id,image_url,image_urls)').eq('borrower_id',uid).in('status',['pending','accepted','approved']).order('start_date',{ascending:false});if(reqErr)throw reqErr;
  const reqRows:any[]=(reqs??[])as any[];const ownerIds=Array.from(new Set(reqRows.map(r=>r?.horse?.owner_id).filter((v)=>typeof v==='string'&&v.length>0)))as string[];let ownersById:Record<string,ProfileMini>={};
  if(ownerIds.length){const{data:owners}=await supabase.from('public_profiles').select('id,display_name,full_name').in('id',ownerIds);for(const p of(owners??[])as ProfileMini[])ownersById[p.id]=p}
  const{data:reviews}=reqRows.length?await supabase.from('reviews').select('request_id').in('request_id',reqRows.map(r=>String(r?.id??'')).filter(Boolean)): {data:[]};
  const reviewedIds=new Set(((reviews??[])as any[]).map(r=>String(r.request_id)).filter(Boolean));
  const rows:Ride[]=reqRows.map(r=>{const horse=r?.horse??null;const ownerId=horse?.owner_id?String(horse.owner_id):'';return{id:String(r?.id??''),status:String(r?.status??'pending'),start_date:r?.start_date??null,end_date:r?.end_date??null,message:r?.message??null,horse:horse?.id?{id:String(horse.id),name:horse?.name??null,image_url:horse?.image_url??null,image_urls:Array.isArray(horse?.image_urls)?horse.image_urls.map((v:any)=>String(v)).filter(Boolean):null}:null,horse_id:horse?.id?String(horse.id):null,borrower_name:ownerLabel(ownerId?ownersById[ownerId]:null)}}).filter(x=>x.id);
  if(!cancelled){setRides(rows);setReviewedRequestIds(reviewedIds)}}catch(e:any){if(!cancelled){setError(e?.message??'Failed to load your rides.');setRides([])}}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[]);
 const today=new Date().toISOString().slice(0,10);
 const getRideState=(ride:Ride)=>{
  const past=!!ride.end_date&&ride.end_date.slice(0,10)<today;
  if(ride.status==='pending'&&past)return{label:'Request expired',tone:'grey',past:true,completed:false,reviewDue:false};
  if(ride.status==='pending')return{label:'Awaiting owner response',tone:'navy',past:false,completed:false,reviewDue:false};
  if(past&&reviewedRequestIds.has(ride.id))return{label:'Completed',tone:'gold',past:true,completed:true,reviewDue:false};
  if(past)return{label:'Completed — review due',tone:'red',past:true,completed:false,reviewDue:true};
  return{label:'Upcoming confirmed ride',tone:'green',past:false,completed:false,reviewDue:false};
 };
 const pastRides=useMemo(()=>rides.filter(r=>!!r.end_date&&r.end_date.slice(0,10)<today).length,[rides,today]);
 const upcoming=useMemo(()=>rides.filter(r=>!!r.end_date&&r.end_date.slice(0,10)>=today&&r.status!=='pending').length,[rides,today]);
 return <div className="pmp-pageShell"><style>{`
 .pmp-ridesHeader{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap}.pmp-ridesBack{width:max-content!important;max-width:max-content!important;flex:0 0 auto}.pmp-ridesActions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;width:min(100%,420px)}.pmp-ridesActions a{width:100%;box-sizing:border-box;justify-content:center}.pmp-rideGrid{display:grid;gap:12px;margin-top:14px}.pmp-ridesStats{grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:12px}.pmp-ridesStats .pmp-statCard{padding:11px 10px}.pmp-ridesStats .pmp-statLabel{font-size:10px;letter-spacing:.03em}.pmp-ridesStats .pmp-statValue{font-size:1.55rem;margin-top:4px}.pmp-rideCard{border:1px solid rgba(200,162,77,.24);border-radius:24px;background:linear-gradient(145deg,rgba(255,255,255,.98),rgba(245,241,232,.78));box-shadow:0 16px 38px rgba(31,42,68,.065);padding:20px}.pmp-rideCard.pmp-rideReviewDue{border-color:rgba(163,58,58,.26);background:linear-gradient(145deg,rgba(255,255,255,.98),rgba(163,58,58,.045))}.pmp-rideCard.pmp-rideCompleted{border-color:rgba(200,162,77,.34);background:linear-gradient(145deg,rgba(255,255,255,.98),rgba(200,162,77,.07))}.pmp-rideTop{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;flex-wrap:wrap}.pmp-rideHorse{font-size:18px;font-weight:850;color:#1F2A44;letter-spacing:-.02em}.pmp-rideMeta{margin-top:5px;font-size:13px;color:rgba(31,42,68,.66)}.pmp-rideDates{margin-top:12px;padding:12px 14px;border-radius:16px;background:rgba(31,61,43,.075);color:#1F3D2B;font-weight:800;font-size:13px;border:1px solid rgba(31,61,43,.08)}.pmp-rideActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.pmp-rideActions a{min-height:42px;gap:9px}.pmp-rideActions a svg{margin-right:2px;flex:0 0 auto}@media(max-width:560px){.pmp-ridesStats{grid-template-columns:repeat(3,minmax(0,1fr))}.pmp-rideActions{display:grid;grid-template-columns:1fr}.pmp-rideActions a{width:100%;box-sizing:border-box;justify-content:center}.pmp-ridesActions{width:100%;grid-template-columns:repeat(2,minmax(0,1fr))}}
 `}</style>
 <div className="pmp-ridesHeader"><div><Link href="/dashboard" className="pmp-ctaSecondary pmp-ridesBack" style={{textDecoration:'none',minHeight:40}}>← Dashboard</Link><div className="pmp-kicker" style={{marginTop:16}}>Your riding</div><h1 className="pmp-pageTitle">My rides</h1><div className="pmp-mutedText" style={{marginTop:6}}>Keep track of your bookings, owners and reviews.</div></div><div className="pmp-ridesActions"><Link href="/browse" className="pmp-ctaPrimary"><Icon name="search" size={17}/> Browse horses</Link><Link href="/messages" className="pmp-ctaSecondary"><Icon name="messages" size={17}/> Messages</Link></div></div>
 <section className="pmp-statGrid pmp-ridesStats"><article className="pmp-statCard"><div className="pmp-statLabel">Your rides</div><div className="pmp-statValue">{rides.length}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">Upcoming</div><div className="pmp-statValue">{upcoming}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">Past bookings</div><div className="pmp-statValue">{pastRides}</div></article></section>
 {loading?<div style={{marginTop:16}} className="pmp-mutedText">Loading your rides…</div>:null}{error?<div className="pmp-errorBanner" style={{marginTop:16}}>{error}</div>:null}{!myUserId&&!loading?<div className="pmp-sectionCard" style={{marginTop:16}}>Log in to see your rides.</div>:null}
 {myUserId?<div className="pmp-rideGrid">{!loading&&!error&&rides.length===0?<div className="pmp-sectionCard"><div className="pmp-emptyState"><div className="pmp-emptyIcon"><Icon name="calendar" size={31}/></div><div className="pmp-emptyTitle">No approved rides yet</div><div className="pmp-emptyText">Browse horses to find a listing and send a request.</div><Link href="/browse" className="pmp-ctaPrimary" style={{marginTop:12}}>Browse horses</Link></div></div>:null}
 {rides.map(ride=>{const state=getRideState(ride);const tone=state.tone==='green'?{color:'#1F3D2B',background:'rgba(31,61,43,.09)',borderColor:'rgba(31,61,43,.16)'}:state.tone==='red'?{color:'#A33A3A',background:'rgba(163,58,58,.09)',borderColor:'rgba(163,58,58,.18)'}:state.tone==='gold'?{color:'#8A6818',background:'rgba(200,162,77,.14)',borderColor:'rgba(200,162,77,.30)'}:{color:'#1F2A44',background:'rgba(31,42,68,.07)',borderColor:'rgba(31,42,68,.13)'};return <article key={ride.id} className={`pmp-rideCard${state.past?' pmp-ridePast':''}${state.reviewDue?' pmp-rideReviewDue':''}${state.completed?' pmp-rideCompleted':''}`}><div className="pmp-rideTop"><div><div className="pmp-kicker" style={{color:tone.color,fontSize:13,fontWeight:850,textTransform:'none'}}>{state.label}</div><div className="pmp-rideHorse">{ride.horse?.name??'Horse'}</div><div className="pmp-rideMeta">Owner: <strong>{ride.borrower_name}</strong></div></div>{ride.horse?.image_url||ride.horse?.image_urls?.[0]?<img src={ride.horse.image_url||ride.horse.image_urls?.[0]||''} alt={ride.horse?.name||'Horse'} style={{width:88,height:72,objectFit:'cover',borderRadius:16,border:'1px solid rgba(200,162,77,.25)',boxShadow:'0 8px 18px rgba(31,42,68,.08)'}}/>:null}<span style={{display:'inline-flex',alignItems:'center',padding:'6px 10px',borderRadius:999,background:tone.background,border:'1px solid '+tone.borderColor,color:tone.color,fontSize:12,fontWeight:950}}>{state.label}</span></div><div className="pmp-rideDates">{fmtDate(ride.start_date)} → {fmtDate(ride.end_date)}</div>{state.reviewDue?<div className="pmp-mutedText" style={{marginTop:10}}>Your booking has finished. Leave a review to complete your ride.</div>:state.label==='Request expired'?<div className="pmp-mutedText" style={{marginTop:10}}>The requested dates have passed without owner approval.</div>:state.completed?<div className="pmp-mutedText" style={{marginTop:10}}>This ride is complete. Thank you for leaving a review.</div>:ride.status!=='pending'&&ride.message?.trim()?<div className="pmp-mutedText" style={{marginTop:10}}>Your request: {ride.message.trim()}</div>:null}<div className="pmp-rideActions"><Link href={`/messages/${ride.id}`} className="pmp-ctaSecondary"><Icon name="messages" size={16}/> {state.label==='Request expired'?'Message owner':'Message owner'}</Link>{state.reviewDue?<Link href={`/review/${ride.id}`} className="pmp-ctaPrimary">Leave a review</Link>:!state.past&&ride.horse_id?<Link href={`/horse/${ride.horse_id}`} className="pmp-ctaSecondary">View horse</Link>:null}</div></article>})}</div>:null}
 </div>;
}
