'use client';

export const dynamic = 'force-dynamic';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { AvailabilityBadge } from '@/components/AvailabilityBadge';
import { userFacingError } from '@/lib/userFacingError';
import { Icon } from '@/components/Icon';

const palette={forest:'#1F3D2B',navy:'#1F2A44'};
type HorseRow={id:string;name:string|null};
type ProfileSetup={display_name:string|null;avatar_url:string|null;location:string|null;bio:string|null};
type BlockRow={id:string;horse_id:string;start_date:string;end_date:string;reason:string|null};
type BookingRow={id:string;horse_id:string;start_date:string;end_date:string};
type UnifiedRange={kind:'blocked'|'booking';horseId:string;startDate:string;endDate:string;label:string;sourceId:string};
function todayISODate(){return new Date().toISOString().slice(0,10)}

export default function DashboardOverview(){
 const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[horses,setHorses]=useState<HorseRow[]>([]);const[ranges,setRanges]=useState<UnifiedRange[]>([]);const[profileSetup,setProfileSetup]=useState<ProfileSetup|null>(null);const[pendingRequests,setPendingRequests]=useState(0);
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError(null);try{const{data:{user},error:userErr}=await supabase.auth.getUser();if(userErr)throw userErr;if(!user)throw new Error('Not authenticated');const[horsesRes,profileRes]=await Promise.all([supabase.from('horses').select('id,name').eq('owner_id',user.id).order('created_at',{ascending:false}),supabase.from('profiles').select('display_name,avatar_url,location,bio').eq('id',user.id).maybeSingle()]);if(horsesRes.error)throw horsesRes.error;if(profileRes.error)throw profileRes.error;const horseRows=(horsesRes.data??[])as HorseRow[];if(cancelled)return;setHorses(horseRows);setProfileSetup((profileRes.data??null)as ProfileSetup|null);const horseIds=horseRows.map(h=>h.id);if(!horseIds.length){setRanges([]);setPendingRequests(0);setLoading(false);return}const today=todayISODate();const[blocksRes,bookingsRes,pendingRes]=await Promise.all([supabase.from('horse_unavailability').select('id,horse_id,start_date,end_date,reason').in('horse_id',horseIds).not('start_date','is',null).not('end_date','is',null).gte('end_date',today).order('start_date',{ascending:true}),supabase.from('borrow_requests').select('id,horse_id,start_date,end_date,status').in('horse_id',horseIds).in('status',['approved','accepted']).not('start_date','is',null).not('end_date','is',null).gte('end_date',today).order('start_date',{ascending:true}),supabase.from('borrow_requests').select('id',{count:'exact',head:true}).in('horse_id',horseIds).eq('status','pending')]);if(cancelled)return;if(blocksRes.error)throw blocksRes.error;if(bookingsRes.error)throw bookingsRes.error;if(pendingRes.error)throw pendingRes.error;const blocks=(blocksRes.data??[])as BlockRow[];const bookings=(bookingsRes.data??[])as BookingRow[];setPendingRequests(pendingRes.count??0);setRanges([...blocks.map(b=>({kind:'blocked'as const,horseId:b.horse_id,startDate:b.start_date,endDate:b.end_date,label:b.reason?.trim()?b.reason.trim():'Blocked',sourceId:b.id})),...bookings.map(br=>({kind:'booking'as const,horseId:br.horse_id,startDate:br.start_date,endDate:br.end_date,label:'Approved booking',sourceId:br.id}))].sort((a,b)=>a.startDate.localeCompare(b.startDate)));setLoading(false)}catch(e:any){if(!cancelled)setError(userFacingError(e,'We couldn’t load your dashboard. Please try again.'));if(!cancelled)setRanges([]);setLoading(false)}}load();const reqCh=supabase.channel('dashboard-request-count').on('postgres_changes',{event:'*',schema:'public',table:'borrow_requests'},()=>void load()).subscribe();const blockCh=supabase.channel('dashboard-block-count').on('postgres_changes',{event:'*',schema:'public',table:'horse_unavailability'},()=>void load()).subscribe();return()=>{cancelled=true;supabase.removeChannel(reqCh);supabase.removeChannel(blockCh)}},[]);
 const horseNameById=useMemo(()=>{const m=new Map<string,string>();for(const h of horses)m.set(h.id,h.name??'Horse');return m},[horses]);const upcoming=useMemo(()=>ranges.slice(0,8),[ranges]);const bookingCount=useMemo(()=>ranges.filter(r=>r.kind==='booking').length,[ranges]);const blockedCount=useMemo(()=>ranges.filter(r=>r.kind==='blocked').length,[ranges]);const setupItems=useMemo(()=>[{label:'Choose a display name',done:!!profileSetup?.display_name?.trim()},{label:'Add a profile photo',done:!!profileSetup?.avatar_url?.trim()},{label:'Add your general location',done:!!profileSetup?.location?.trim()},{label:'Tell the community about you',done:!!profileSetup?.bio?.trim()}],[profileSetup]);const setupComplete=setupItems.every(i=>i.done);
 return <div className="pmp-pageShell"><style>{`
 .pmp-dashboardActions{margin-top:18px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.pmp-dashboardAction{position:relative;min-height:66px;border:1px solid rgba(31,42,68,.12);border-radius:17px;background:#fff;text-decoration:none;color:#1f2a44;padding:13px 14px;display:flex;align-items:center;gap:11px;font-weight:950;box-shadow:0 10px 24px rgba(31,42,68,.05)}.pmp-dashboardAction.primary{background:#173d2c;color:#fff;border-color:#173d2c}.pmp-dashboardAction small{display:block;font-size:11px;font-weight:750;opacity:.7;margin-top:3px}.pmp-dashboardActionIcon{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:rgba(31,61,43,.08);flex:0 0 auto}.pmp-dashboardAction.primary .pmp-dashboardActionIcon{background:rgba(255,255,255,.14)}.pmp-dashboardBadge{position:absolute;right:10px;top:9px;min-width:21px;height:21px;padding:0 6px;border-radius:999px;background:#111827;color:#fff;font-size:11px;display:flex;align-items:center;justify-content:center}.pmp-dashboardAction.primary .pmp-dashboardBadge{background:#fff;color:#173d2c}
 @media(max-width:560px){.pmp-dashboardActions{grid-template-columns:1fr}.pmp-dashboardAction{min-height:62px}.pmp-pageShell{overflow-x:hidden}}
 `}</style>
 <div><div className="pmp-kicker">Your account</div><h1 className="pmp-pageTitle">Dashboard</h1><div className="pmp-mutedText" style={{marginTop:6}}>Everything you need to ride, manage your horses and respond to requests.</div></div>
 <div className="pmp-dashboardActions">
  <Link href="/dashboard/borrower/horses" className="pmp-dashboardAction primary"><span className="pmp-dashboardActionIcon"><Icon name="calendar" size={20}/></span><span>My rides<small>Bookings, messages & leave reviews</small></span></Link>
  <Link href="/dashboard/owner/horses" className="pmp-dashboardAction"><span className="pmp-dashboardActionIcon"><Icon name="horseshoe" size={20}/></span><span>My horses<small>Edit listings & availability</small></span></Link>
  <Link href="/dashboard/owner/requests" className="pmp-dashboardAction"><span className="pmp-dashboardActionIcon"><Icon name="messages" size={20}/></span><span>Horse requests<small>Approve or decline requests</small></span>{pendingRequests>0?<span className="pmp-dashboardBadge">{pendingRequests>99?'99+':pendingRequests}</span>:null}</Link>
  <Link href="/dashboard/owner/horses/add" className="pmp-dashboardAction"><span className="pmp-dashboardActionIcon"><Icon name="plus" size={20}/></span><span>List a horse<small>Create a new listing</small></span></Link>
  <Link href="/browse" className="pmp-dashboardAction"><span className="pmp-dashboardActionIcon"><Icon name="search" size={20}/></span><span>Browse horses<small>Find your next ride</small></span></Link>
  <Link href="/dashboard/membership" className="pmp-dashboardAction"><span className="pmp-dashboardActionIcon"><Icon name="credit-card" size={20}/></span><span>Membership<small>Manage your plan</small></span></Link>
 </div>
 <section className="pmp-statGrid" style={{marginTop:16}}><article className="pmp-statCard"><div className="pmp-statLabel">Active horses</div><div className="pmp-statValue">{horses.length}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">Upcoming bookings</div><div className="pmp-statValue">{bookingCount}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">Upcoming blocks</div><div className="pmp-statValue">{blockedCount}</div></article><article className="pmp-statCard"><div className="pmp-statLabel">Pending requests</div><div className="pmp-statValue">{pendingRequests}</div></article></section>
 {loading?<div style={{marginTop:16}} className="pmp-mutedText">Loading…</div>:null}{error?<div className="pmp-errorBanner" style={{marginTop:16}}>{error}</div>:null}
 {!loading&&!error&&!setupComplete?<section className="pmp-sectionCard" style={{marginTop:12}}><div className="pmp-sectionHeader"><div><div className="pmp-kicker">Getting started</div><h3 className="pmp-sectionTitle">Complete your profile</h3></div><Link href="/profile" className="pmp-ctaPrimary">Update profile</Link></div><div className="pmp-listStack" style={{marginTop:12}}>{setupItems.map(item=><div key={item.label} className="pmp-horseRowCard" style={{display:'flex',alignItems:'center',gap:10}}><span aria-hidden="true">{item.done?<Icon name="check" size={17}/>:<span className="pmp-progressDot"/>}</span><span style={{fontWeight:item.done?800:950,opacity:item.done?0.66:1}}>{item.label}</span></div>)}</div></section>:null}
 <section className="pmp-sectionCard" style={{marginTop:12}}><div className="pmp-sectionHeader"><div><div className="pmp-kicker">Upcoming activity</div><h3 className="pmp-sectionTitle">Your next dates</h3></div><div className="pmp-mutedText">{ranges.length} upcoming range{ranges.length===1?'':'s'}</div></div>{!loading&&!error&&upcoming.length===0?<div className="pmp-emptyState"><div className="pmp-emptyIcon"><Icon name="calendar" size={31}/></div><div className="pmp-emptyTitle">No upcoming activity</div><div className="pmp-emptyText">Your approved rides and horse availability will appear here.</div></div>:<div className="pmp-listStack">{upcoming.map(r=><div key={`${r.kind}-${r.sourceId}`} className="pmp-horseRowCard" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div style={{minWidth:0}}><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><AvailabilityBadge label={r.kind==='blocked'?'Blocked':'Booking'} tone={r.kind==='blocked'?'warn':'info'}/><div style={{fontWeight:950,color:palette.navy}}>{horseNameById.get(r.horseId)??'Horse'}</div></div><div style={{marginTop:8,fontSize:13,color:'rgba(0,0,0,.70)'}}><strong>{r.startDate}</strong> → <strong>{r.endDate}</strong> — {r.label}</div></div><Link href={`/dashboard/owner/horses/${r.horseId}/availability`} className="pmp-ctaSecondary">Availability</Link></div>)}</div>}</section>
 </div>;
}
